import java.util.ArrayList;
import java.util.function.Supplier;

public class SupplierPrimeGenerator {
    public static void main(String[] args) {
        // Define a Supplier that computes and packs the first 10 prime values
        Supplier<ArrayList<Integer>> primeSupplier = () -> {
            ArrayList<Integer> primes = new ArrayList<>();
            int count = 0;
            int num = 2; // Starting verification point

            while (count < 10) {
                if (isPrime(num)) {
                    primes.add(num);
                    count++;
                }
                num++;
            }
            return primes;
        };

        // Retrieve generated list output data from Supplier configuration
        ArrayList<Integer> firstTenPrimes = primeSupplier.get();
        System.out.println("First 10 prime numbers generated by Supplier: " + firstTenPrimes);
    }

    // Checking prime logical standard condition helper method
    private static boolean isPrime(int n) {
        if (n <= 1) return false;
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) return false;
        }
        return true;
    }
}
